//! Golden tests: compare kawat extract() output against Python trafilatura.
//!
//! Fixtures and expected outputs are generated by `golden/generate.py`.

use std::collections::HashSet;
use std::fs;
use std::path::PathBuf;

const FIXTURES_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden");
const ACCEPTANCE_THRESHOLD: f64 = 0.70;

/// Compute Jaccard similarity between two strings (tokenized by whitespace).
fn jaccard_similarity(a: &str, b: &str) -> f64 {
    let tokens_a: HashSet<String> = a.split_whitespace().map(|s| s.to_lowercase()).collect();
    let tokens_b: HashSet<String> = b.split_whitespace().map(|s| s.to_lowercase()).collect();

    if tokens_a.is_empty() && tokens_b.is_empty() {
        return 1.0;
    }
    if tokens_a.is_empty() || tokens_b.is_empty() {
        return 0.0;
    }

    let intersection: HashSet<_> = tokens_a.intersection(&tokens_b).collect();
    let union: HashSet<_> = tokens_a.union(&tokens_b).collect();

    intersection.len() as f64 / union.len() as f64
}

/// Compute word-level containment: how many expected words appear in actual.
/// Uses whole-word matching (HashSet) instead of substring search to avoid
/// false positives (e.g. "a" matching inside "article").
fn containment(actual: &str, expected: &str) -> f64 {
    let actual_lower = actual.to_lowercase();
    let expected_lower = expected.to_lowercase();

    if expected_lower.is_empty() {
        return if actual_lower.is_empty() { 1.0 } else { 0.0 };
    }

    let expected_words: Vec<&str> = expected_lower.split_whitespace().collect();
    if expected_words.is_empty() {
        return 1.0;
    }

    let actual_words: HashSet<&str> = actual_lower.split_whitespace().collect();
    let matched = expected_words
        .iter()
        .filter(|w| actual_words.contains(**w))
        .count();

    matched as f64 / expected_words.len() as f64
}

/// Combined similarity: average of Jaccard and containment.
fn similarity_score(actual: &str, expected: &str) -> f64 {
    let jaccard = jaccard_similarity(actual, expected);
    let contain = containment(actual, expected);
    (jaccard + contain) / 2.0
}

#[test]
fn golden_test_suite() {
    let fixtures_dir = PathBuf::from(FIXTURES_DIR);
    let metadata_path = fixtures_dir.join("metadata.json");

    let metadata_str = fs::read_to_string(&metadata_path)
        .expect("metadata.json should exist; run generate.py to create fixtures");
    let metadata: Vec<serde_json::Value> =
        serde_json::from_str(&metadata_str).expect("metadata.json should be valid JSON");

    let mut scores = Vec::new();
    let mut failures = Vec::new();

    for entry in metadata {
        let name = entry["name"]
            .as_str()
            .expect("field 'name' missing in metadata entry");
        let html_file = entry["html_file"]
            .as_str()
            .expect("field 'html_file' missing in metadata entry");
        let expected_file = entry["expected_file"]
            .as_str()
            .expect("field 'expected_file' missing in metadata entry");

        let html_path = fixtures_dir.join(html_file);
        let expected_path = fixtures_dir.join(expected_file);

        let html = fs::read_to_string(&html_path)
            .unwrap_or_else(|e| panic!("Failed to read fixture {html_path:?}: {e}"));
        let expected = fs::read_to_string(&expected_path)
            .unwrap_or_else(|e| panic!("Failed to read expected output {expected_path:?}: {e}"));

        let options = kawat::ExtractorOptions {
            min_extracted_size: 1, // allow all fixtures through for comparison
            ..Default::default()
        };
        let actual = match kawat::extract(&html, &options) {
            Ok(text) => text,
            Err(e) => {
                failures.push(format!("{name}: extraction failed: {e}"));
                continue;
            }
        };

        let score = similarity_score(&actual, &expected);
        scores.push((name.to_string(), score, expected.len(), actual.len()));
    }

    // Print summary table
    println!("\n{:-<60}", "");
    println!(
        "{:>20} {:>10} {:>10} {:>10}",
        "Fixture", "Score", "Expected", "Actual"
    );
    println!("{:-<60}", "");
    for (name, score, expected_len, actual_len) in &scores {
        let status = if *score >= ACCEPTANCE_THRESHOLD {
            "✓"
        } else {
            "✗"
        };
        println!(
            "{:>20} {:>9.1}% {:>10} {:>10} {}",
            name,
            score * 100.0,
            expected_len,
            actual_len,
            status
        );
    }
    println!("{:-<60}", "");

    if !failures.is_empty() {
        println!("\nFailures:");
        for f in &failures {
            println!("  - {f}");
        }
    }

    let avg_score = if scores.is_empty() {
        0.0
    } else {
        scores.iter().map(|(_, s, _, _)| s).sum::<f64>() / scores.len() as f64
    };

    let passing = scores
        .iter()
        .filter(|(_, s, _, _)| *s >= ACCEPTANCE_THRESHOLD)
        .count();
    let total = scores.len() + failures.len();

    println!(
        "\nSummary: {passing}/{total} passing (avg score: {:.1}%)",
        avg_score * 100.0
    );

    // Assertion 1: at least ACCEPTANCE_THRESHOLD fraction of fixtures must pass
    let passing_rate = passing as f64 / total as f64;
    assert!(
        passing_rate >= ACCEPTANCE_THRESHOLD,
        "Only {passing}/{total} fixtures pass ({}.{:0>2}%), need >= {:.0}%",
        (passing_rate * 100.0) as usize,
        ((passing_rate * 100.0).fract() * 100.0) as usize,
        ACCEPTANCE_THRESHOLD * 100.0
    );

    // Assertion 2: average score must also meet threshold
    assert!(
        avg_score >= ACCEPTANCE_THRESHOLD,
        "Average golden test score {:.1}% below threshold {:.1}%",
        avg_score * 100.0,
        ACCEPTANCE_THRESHOLD * 100.0
    );
}
